### ISSUE TITLE
name' is unavailable: not available on iOS

### ISSUE THREAD

**Issue by NarayanaMV** [tombenner/nui#379]
name' is unavailable: not available on iOS

/Pods/NUIParse/NUIParse/Parsers/NUIPShiftReduceParsers/NUIPShiftReduceGotoTable.m:85:58: error: 'name' is unavailable: not available on iOS
    return [(NSNumber *)[table[state] objectForKey:[rule name]] unsignedIntegerValue];

---> We are getting this issue while working on IOS 13.0 using XCode11 beta 6 version.

Please let us know the fix/update if any.

**Comment by NarayanaMV** [comment]
![Screenshot 2019-08-22 at 1 29 00 PM](https://user-images.githubusercontent.com/26486965/63497331-26412500-c4e1-11e9-9d23-fd831139c3f8.png)

**Comment by ataranlen** [comment]
I ended up having to wipe every trace of xCode from my machine aside from the application itself and restart my machine in order to get past this error.

**Comment by Arun30sep** [comment]
Is this issue resolved? I've cleared all processes and restarted the system as well. but I'm still not able to resolve this issue.

**Comment by paulgee31** [comment]
The only way I was able to move past this was to alter NUIPRule.h and NUIPRule.m and rename the name property to pname and replace any reference to it in the rest of the NUI classes. Not ideal but allowed my project to build again.

**Comment by IlyaBoryanScopeTech** [comment]
I fixed this issue adding a separate getter for the "name" variable. Details are in the my [commit](https://github.com/tombenner/NUIParse/pull/10/commits/5219e49ddc5248113f04e818b89aaca232ab5f38)

**Comment by Emailrus** [comment]
NUIPShiftReduceGotoTable is missing import of NUIPRule.h

**Comment by IlyaBoryanScopeTech** [comment]
> NUIPShiftReduceGotoTable is missing import of NUIPRule.h
There is #import <NUIParse/NUIParse.h>

**Comment by Emailrus** [comment]
> > NUIPShiftReduceGotoTable is missing import of NUIPRule.h
> > There is #import <NUIParse/NUIParse.h>

Nope
https://github.com/tombenner/nui/blob/v0.5.5/Demo/Pods/NUIParse/NUIParse/Parsers/NUIPShiftReduceParsers/NUIPShiftReduceGotoTable.h
https://github.com/tombenner/nui/blob/v0.5.5/Demo/Pods/NUIParse/NUIParse/Parsers/NUIPShiftReduceParsers/NUIPShiftReduceGotoTable.m

**Comment by IlyaBoryanScopeTech** [comment]
I am not an owner of this repo. Just fixed the issue and created a pull request from my repo. It is still waiting for review.
[Pull request](https://github.com/tombenner/NUIParse/pull/10)

**Comment by Emailrus** [comment]
I was talking about how to fix this error: all you need to do here is to add missing import in this file. Also this repo had a lot of changes made in non-master branch, so it's unlikely that any PR to master will go through

**Comment by IlyaBoryanScopeTech** [comment]
@Emailrus You are right. 
#import "NUIParse.h" in NUIPShiftReduceGotoTable solves the problem. I did some extra work ))
So, the only way for now is manually update above mentioned class on the your computer.

**Comment by hilalbaig** [comment]
In case if someone is facing issue while running pod with @IlyaBoryanScopeTech's solution

```
def nuiparse_overrides
    pod 'NUIParse', :git => "https://github.com/IlyaBoryanScopeTech/NUIParse.git"
end

target 'MyProject' do
    nuiparse_overrides

    pod 'NUI' # This podspec still references 'NUIParse' but is overridden above
    pod # ...
end
```

**Comment by IlyaBoryanScopeTech** [comment]
@hilalbaig Great advice! Thanks!

**Comment by fpaaske** [comment]
You can also use @hilalbaig's technique with https://github.com/tombenner/NUIParse.git now.
